export const ERROR_CODE = {
  USER_PHONE_EXISTS: 'U001',
  USER_NOT_FOUND: 'U002',
  USER_INVALID_EMAIL: 'U003',
  USER_ID_MISSING: 'U004',

  // Auth
  AUTH_UNAUTHORIZED: 'A001',
  AUTH_TOKEN_EXPIRED: 'A002',
  AUTH_INVALID_CREDENTIALS: 'A003',

  // Device
  DEVICE_NOT_FOUND: 'D001',
  DEVICE_FORBIDDEN: 'D002',
  DEVICE_INACTIVATED: 'D003',

  REDIS_AUTH_REUSE_DETECTED: 'R001',
  REDIS_AUTH_PREV_JTI_REQUIRED: 'R002',
  REDIS_AUTH_TOKEN_EXPIRED: 'R003',
  REDIS_AUTH_DEVICE_MISMATCH: 'R004',
  REDIS_AUTH_TOKEN_NOT_IN_FAMILY: 'R005',
  REDIS_AUTH_FAMILY_NOT_FOUND: 'R006',
  REDIS_AUTH_ABSOLUTE_EXPIRY_EXCEEDED: 'R007',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
