
export const ERROR_CODE: Record<string, string> = {
  // User
  USER_PHONE_EXISTS: 'USR_1001',
  USER_NOT_FOUND: 'USR_1002',
  USER_INVALID_EMAIL: 'USR_1001',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_2001',
  AUTH_TOKEN_EXPIRED: 'AUTH_2002',

  // Device
  DEVICE_NOT_FOUND: 'DEV_3001',
  DEVICE_FORBIDDEN: 'DEV_3002',
  DEVICE_INACTIVATED: 'DEV_3003',

  REDIS_AUTH_REUSE_DETECTED: 'REDIS_AUTH_4001',
  REDIS_AUTH_PREV_JTI_REQUIRED: 'REDIS_AUTH_4002',
  REDIS_AUTH_TOKEN_EXPIRED: 'REDIS_AUTH_4003',
  REDIS_AUTH_DEVICE_MISMATCH: 'REDIS_AUTH_4004',
  REDIS_AUTH_TOKEN_NOT_IN_FAMILY: 'REDIS_AUTH_4005',
  REDIS_AUTH_FAMILY_NOT_FOUND: 'REDIS_AUTH_4006',
  REDIS_AUTH_ABSOLUTE_EXPIRY_EXCEEDED: 'REDIS_AUTH_4007',
} as const;

export type ErrorCode = keyof typeof ERROR_CODE;
